DROP TABLE IF EXISTS PASSAGEIRO;
CREATE TABLE PASSAGEIRO(
    Numero_CC TEXT PRIMARY KEY,
    Nome TEXT NOT NULL, 
    Data_de_Nascimento DATE NOT NULL, 
    Check_Vacinacao_Necessaria INTEGER NOT NULL,
    ID_Passaporte TEXT NOT NULL UNIQUE,
    CHECK(Check_Vacinacao_Necessaria=1)
);
SELECT Numero_CC, Data_de_Nascimento, (JULIANDAY('now')-JULIANDAY(Data_de_Nascimento)) / 365 AS Idade FROM PASSAGEIRO;

DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
    Numero_CC TEXT PRIMARY KEY,
    IBAN TEXT UNIQUE,
    NIF TEXT UNIQUE,
    Email TEXT NOT NULL,
    Numero_de_Telefone TEXT NOT NULL,
    Morada_de_Faturacao TEXT,
    FOREIGN KEY (Numero_CC) REFERENCES PASSAGEIRO(Numero_CC) ON DELETE CASCADE
);

DROP TABLE IF EXISTS CIDADE;
CREATE TABLE CIDADE (
    Nome TEXT PRIMARY KEY,
    Regiao TEXT,
    Pais TEXT NOT NULL
);

DROP TABLE IF EXISTS AVIAO;
CREATE TABLE AVIAO(
    ID_Aviao INTEGER PRIMARY KEY,
    Modelo TEXT NOT NULL,
    Companhia_Aerea TEXT NOT NULL,
    Capacidade INTEGER NOT NULL,
    Ano_de_Producao INTEGER NOT NULL
);

DROP TABLE IF EXISTS ALOJAMENTO;
CREATE TABLE ALOJAMENTO(
    ID_de_Alojamento TEXT PRIMARY KEY,
    Endereco TEXT NOT NULL,
    Cidade TEXT NOT NULL,
    Check_in DATE NOT NULL,
    Check_out DATE NOT NULL,
    Numero_de_Quartos INTEGER NOT NULL,
    Numero_de_Telefone INTEGER NOT NULL,
    Avaliacao REAL,
    FOREIGN KEY (Cidade) REFERENCES CIDADE(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK(Check_in<Check_out)
);

DROP TABLE IF EXISTS AEROPORTO;
CREATE TABLE AEROPORTO (
    ID_de_Aeroporto TEXT PRIMARY KEY,
    Nome TEXT NOT NULL,
    Porta_de_Embarque INTEGER NOT NULL,
    Cidade TEXT NOT NULL,
    FOREIGN KEY (Cidade) REFERENCES CIDADE(Nome) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS VIAGEM;
CREATE TABLE VIAGEM(
    ID_da_Rota TEXT PRIMARY KEY,
    Estado_da_Viagem INTEGER NOT NULL,
    Hora_de_Embarque TIME NOT NULL,
    Hora_de_Chegada TIME NOT NULL,
    Cidade_de_Embarque TEXT NOT NULL,
    Cidade_de_Chegada TEXT NOT NULL,
    ID_Aviao TEXT NOT NULL,
    FOREIGN KEY (Cidade_de_Embarque) REFERENCES CIDADE(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Cidade_de_Chegada) REFERENCES CIDADE(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Aviao) REFERENCES AVIAO(ID_Aviao) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (Cidade_de_Embarque <> Cidade_de_Chegada)
);

DROP TABLE IF EXISTS ROTA;
CREATE TABLE ROTA(
    ID_Voo INTEGER PRIMARY KEY,
    ID_da_Rota TEXT,
    Aeroporto_de_Partida TEXT,
    Aeroporto_de_Chegada TEXT,
    Hora_de_Partida TIME,
    Hora_de_Chegada TIME,
    FOREIGN KEY (ID_da_Rota) REFERENCES VIAGEM(ID_da_Rota) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Aeroporto_de_Partida) REFERENCES AEROPORTO(ID_de_Aeroporto) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Aeroporto_de_Chegada) REFERENCES AEROPORTO(ID_de_Aeroporto) ON DELETE CASCADE ON UPDATE CASCADE
);
SELECT (STRFTIME('%s', Hora_de_Chegada) - STRFTIME('%s', Hora_de_Partida)) / 60 AS Tempo_de_Espera FROM ROTA;

DROP TABLE IF EXISTS RESERVA;
CREATE TABLE RESERVA(
    ID_da_Reserva TEXT PRIMARY KEY,
    Data_de_Inicio DATE NOT NULL,
    Data_de_Fim DATE NOT NULL,
    Bagagem_Total INTEGER NOT NULL CHECK(Bagagem_Total>=0),
    ID_da_Rota TEXT NOT NULL,
    FOREIGN KEY (ID_da_Rota) REFERENCES VIAGEM(ID_da_Rota) ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (Data_de_Fim>Data_de_Inicio)
);
SELECT ID_da_Reserva, Data_de_Inicio,Data_de_Fim, (JULIANDAY(Data_de_Fim)-JULIANDAY(Data_de_Inicio)) AS DIAS FROM RESERVA;

DROP TABLE IF EXISTS PNR;
CREATE TABLE PNR(
    Numero_CC TEXT,
    ID_da_Reserva TEXT,
    PRIMARY KEY (Numero_CC, ID_da_Reserva),
    FOREIGN KEY (Numero_CC) REFERENCES PASSAGEIRO(Numero_CC) ON DELETE CASCADE,
    FOREIGN KEY (ID_da_Reserva) REFERENCES RESERVA(ID_da_Reserva) ON DELETE CASCADE ON UPDATE CASCADE 
);

DROP TABLE IF EXISTS AQUISICAO;
CREATE TABLE AQUISICAO(
    ID_Transacao TEXT PRIMARY KEY,
    Numero_CC TEXT,
    ID_da_Reserva TEXT,
    Data_de_Pagamento DATE,
    Valor_Pago REAL NOT NULL CHECK (Valor_Pago>0),
    Estado_de_Pagamento INTEGER NOT NULL,
    FOREIGN KEY (Numero_CC) REFERENCES CLIENTE(Numero_CC) ON DELETE CASCADE,
    FOREIGN KEY (ID_da_Reserva) REFERENCES  RESERVA(ID_da_Reserva) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS FUNCIONARIO;
CREATE TABLE FUNCIONARIO(
    ID_Funcionario TEXT PRIMARY KEY,
    Nome TEXT NOT NULL,
    Anos_de_Servico INTEGER NOT NULL,
    Salario TEXT NOT NULL,
    Numero_de_Telefone Text NOT NULL UNIQUE,
    Email TEXT NOT NULL UNIQUE,
    NIF TEXT NOT NULL UNIQUE,
    IBAN TEXT NOT NULL UNIQUE  
);

DROP TABLE IF EXISTS GUIA;
CREATE TABLE GUIA(
    ID_Funcionario TEXT PRIMARY KEY,
    Idioma TEXT NOT NULL,
    ID_Diploma_em_Turismo TEXT NOT NULL,
    FOREIGN KEY (ID_Funcionario) REFERENCES FUNCIONARIO(ID_Funcionario) ON DELETE CASCADE 
);

DROP TABLE IF EXISTS TOUR;
CREATE TABLE TOUR(
    ID_de_Tour TEXT PRIMARY KEY,
    Programa TEXT NOT NULL,
    Cidade TEXT NOT NULL,
    ID_Guia TEXT,
    FOREIGN KEY (Cidade) REFERENCES CIDADE(Nome) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Guia) REFERENCES GUIA(ID_Funcionario) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS RESERVA_DE_TOUR;
CREATE TABLE RESERVA_DE_TOUR(
    ID_da_Reserva TEXT, 
    ID_de_Tour TEXT,
    PRIMARY KEY (ID_da_Reserva,ID_de_Tour),
    FOREIGN KEY (ID_da_Reserva) REFERENCES RESERVA(ID_da_Reserva) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_de_Tour) REFERENCES TOUR(ID_de_Tour) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS HOSPEDEIRO;
CREATE TABLE HOSPEDEIRO(
    ID_Funcionario TEXT PRIMARY KEY,
    ID_Certidao_De_Formacao TEXT NOT NULL,
    FOREIGN KEY (ID_Funcionario) REFERENCES FUNCIONARIO(ID_Funcionario) ON DELETE CASCADE 
);

DROP TABLE IF EXISTS PILOTO;
CREATE TABLE PILOTO(
    ID_Funcionario TEXT PRIMARY KEY,
    ID_Licenca TEXT NOT NULL,
    FOREIGN KEY (ID_Funcionario) REFERENCES FUNCIONARIO(ID_Funcionario) ON DELETE CASCADE 
);

DROP TABLE IF EXISTS HOSPEDEIRO_VIAGEM;
CREATE TABLE HOSPEDEIRO_VIAGEM(
    ID_da_Rota TEXT,
    ID_Funcionario TEXT,
    FOREIGN KEY (ID_da_Rota) REFERENCES VIAGEM(ID_da_Rota) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Funcionario) REFERENCES HOSPEDEIRO(ID_Funcionario) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ID_da_Rota, ID_Funcionario)
);

DROP TABLE IF EXISTS PILOTO_VIAGEM;
CREATE TABLE PILOTO_VIAGEM(
    ID_da_Rota TEXT,
    ID_Funcionario TEXT,
    FOREIGN KEY (ID_da_Rota) REFERENCES VIAGEM(ID_da_Rota) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Funcionario) REFERENCES PILOTO(ID_Funcionario) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ID_da_Rota, ID_Funcionario)
);

DROP TABLE IF EXISTS RESERVA_DE_ALOJAMENTO;
CREATE TABLE RESERVA_DE_ALOJAMENTO(
    ID_da_Reserva TEXT, 
    ID_de_Alojamento TEXT,
    PRIMARY KEY (ID_da_Reserva, ID_de_Alojamento),
    FOREIGN KEY (ID_da_Reserva) REFERENCES RESERVA(ID_da_Reserva) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_de_Alojamento) REFERENCES ALOJAMENTO(ID_de_Alojamento) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS ORIENTACAO;
CREATE TABLE ORIENTACAO(
    ID_de_Tour TEXT,
    ID_Funcionario TEXT,
    PRIMARY KEY (ID_de_Tour, ID_Funcionario),
    FOREIGN KEY (ID_de_Tour) REFERENCES TOUR(ID_de_Tour) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_Funcionario) REFERENCES GUIA(ID_Funcionario) ON DELETE CASCADE ON UPDATE CASCADE  
);
